---
- hosts: node
  become: yes
  tasks:
    - name: edit host file
      lineinfile:
        path: /etc/hosts
        line: "ansible.xyzcorp.com 169.168.0.1"
    - name: install ftp
      package:
        name: ftp
        state: latest
    - name: create audit user
      user:
        name: xyzcorp_audit
        state: present
    - name: update motd
      copy:
        src: motd
        dest: /etc/motd
    - name: update issue
      copy:
        src: issue
        dest: /etc/issue
        
- hosts: network
  become: yes
  tasks:
    - name: install netcat
      yum:
        name: nmap-ncat
        state: latest
    - name: create network user
      user:
        name: xyzcorp_network
        state: present
- hosts: sysadmin
  become: yes
  tasks:
    - name: copy tarball to /tmp
      copy:
        src: script.tgz
        dest: /tmp